### ISSUE TITLE
ion-gallery ver 0.1.13 not popping gallery

### ISSUE THREAD

**Issue by ofershap** [pedroabreu/ion-gallery#48] opened 2016-03-16 16:47 UTC
after updating to latest version, tapping on image didnt open the gallery view.
investigating the bug found out that this code inside gallery.html doesn't work properly:
 ng-click="customCallback ? ionItemCallback({item: photo}) : showImage({{photo.position}})">

i havn't configure no callback, just added a simple directive to my code:
        <ion-gallery ion-gallery-items="photos" ion-gallery-row="4"></ion-gallery>

but "showImage" doesn't fire when i tap.  
replacing it back to the old "ng-click="showImage({{photo.position}})" solved the issue.
ofcourse i had to compile the gulp afterward, or just update the minified script at the end of gallery.js too in order for it to work.

FYI if someone having troubles with that. 
@pedroabreu please fix that flaw.. thanks.

**Comment by pedroabreu** [comment] 2016-03-20 14:26
I noticed that I have the same issue now... Don't think I had it when I did the merge but anyway I think the issue is here https://github.com/angular/angular.js/issues/6404

The ionCallback is always evaluated as true even if the function is not passed to the directive. It seems that this is fixed on angular 1.4 so it's an issue for 1.3. I'm implementing now a workaround to check if the function is passed or not

**Comment by pedroabreu** [comment] 2016-03-26 13:21
Fixed with PR #52

**Closed as completed by pedroabreu** 2016-03-26 13:21 UTC
